name: React CI + Deploy With RollBack

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to server after build?'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build/

  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.deploy == 'true' }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: build/

      - name: Set up SSH key and known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem
          ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/do_known_hosts

      - name: Upload new build to DigitalOcean
        run: |
          ssh -i ~/.ssh/key.pem \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=~/.ssh/do_known_hosts \
            ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} "
              cd /www/wwwroot/snvn.deepseahost.com//reactjs
              echo '📦 Backing up current build...'
              mv build build.bak || echo 'No previous build to back up'
            "

          scp -i ~/.ssh/key.pem \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=~/.ssh/do_known_hosts \
            -r build \
            ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }}:/www/wwwroot/snvn.deepseahost.com//reactjs/

      - name: Rollback logic
        run: |
          ssh -i ~/.ssh/key.pem \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=~/.ssh/do_known_hosts \
            ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} "
              cd /www/wwwroot/snvn.deepseahost.com//reactjs
              
              if [ ! -d build ]; then
                echo '❌ Deployment failed. Rolling back...'
                mv build.bak build
                echo '🔁 Rollback complete.'
              else
                echo '✅ Deployment successful.'
              fi
            "
