name: React CI + Deploy With RollBack

on:
  push:
    branches:
      - main
      - master
     

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint || echo "ESLint completed with warnings"

      - name: Build React app
        run: CI=false npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: build/

      - name: Set up SSH key and known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem
          ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/do_known_hosts

      - name: Upload new build to DigitalOcean
        run: |
          ssh -i ~/.ssh/key.pem \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=~/.ssh/do_known_hosts \
            ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} "
              echo '🔪 Killing process on port 3084...'
              PORT=3084
              PID=\$(lsof -t -i:\$PORT)
              if [ -n \"\$PID\" ]; then
                kill -9 \$PID && echo '✅ Process on port \$PORT killed.'
              else
                echo '⚠️ No process found on port \$PORT.'
              fi

              cd /www/wwwroot/CITSNVN/itcrashcourse
              echo '📦 Backing up current build...'
              mv build build.bak || echo 'No previous build to back up'
            "

          scp -i ~/.ssh/key.pem \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=~/.ssh/do_known_hosts \
            -r build \
            ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }}:/www/wwwroot/CITSNVN/itcrashcourse/

      - name: Start server on port 3084
        run: |
          ssh -i ~/.ssh/key.pem \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=~/.ssh/do_known_hosts \
            ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} "
              cd /www/wwwroot/CITSNVN/itcrashcourse/build
              echo '🚀 Starting React app on port 3084...'
              nohup npx serve -s . -l 3084 > serve.log 2>&1 &
              echo '✅ React app started on port 3084.'
            "

      - name: Rollback logic
        run: |
          ssh -i ~/.ssh/key.pem \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=~/.ssh/do_known_hosts \
            ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} "
              cd /www/wwwroot/CITSNVN/itcrashcourse
              if [ ! -d build ]; then
                echo '❌ Deployment failed. Rolling back...'
                mv build.bak build
                echo '🔁 Rollback complete good.'
              else
                echo '✅ Deployment successful.'
              fi
            "
